# 넘파이(Numpy)

# 1. 배열 생성

```
uv add numpy
```

In [1]:
import numpy as np 

## 1) 1차원 배열 생성

In [2]:
data = np.array([1, 2, 3, 4, 5])
print(data)
print(type(data))
data

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [3]:
# 속성
print(data.ndim)  # 차원의 수
print(data.shape) # 배열의 크기

1
(5,)


## 2) 차원별 배열 생성

In [4]:
# 2차원
arr2 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 속성
print(arr2.ndim)  # 차원의 수
print(arr2.shape) # 배열의 크기

2
(2, 3)


In [6]:
# 3차원
arr3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ]
)
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
# 속성
print(arr3.ndim)  # 차원의 수
print(arr3.shape) # 배열의 크기

3
(2, 2, 3)


## 3) 패턴이 있는 배열 생성

In [8]:
# 모든 원소가 0인 배열
arr1 = np.zeros((3, 3))
print(arr1)
# 모든 원소가 1인 배열
arr2 = np.ones((3, 3))
print(arr2)
# 모든 원소가 ?인 배열
arr3 = np.full((3, 3), fill_value=99)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[99 99 99]
 [99 99 99]
 [99 99 99]]


In [9]:
# 난수 생성
arr_random = np.random.random((2, 3)) # 배열의 크기 입력
print(arr_random)

[[0.87273625 0.66486828 0.63173531]
 [0.51748019 0.28182792 0.93310336]]


In [10]:
# 정수인 난수 생성
arr_random_int = np.random.randint(0, 10, 3) # 0부터 10-1까지 3개의 난수를 생성
print(arr_random_int)

[0 3 4]


In [11]:
# 연속된 배열 생성
arr_arange = np.arange(0, 10, 2)
print(arr_arange)

[0 2 4 6 8]


In [12]:
# N등분 한 배열 생성
arr_linspace = np.linspace(0, 1, 10)
print(arr_linspace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 2. 배열 속성

In [13]:
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
data3 = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
])

In [14]:
# .dtype: 배열 안의 요소 타입
# .ndim: 차원의 수
# .shape: 배열의 크기
# .size: 요소의 수

In [15]:
print(data1.dtype)
print(data1.ndim)
print(data1.shape)
print(data1.size)

int64
1
(5,)
5


In [16]:
print(data2.dtype)
print(data2.ndim)
print(data2.shape)
print(data2.size)

int64
2
(2, 3)
6


In [17]:
print(data3.dtype)
print(data3.ndim)
print(data3.shape)
print(data3.size)

int64
3
(2, 3, 2)
12


In [18]:
a = 1
b = 1.0
print(type(a))
print(type(b))

<class 'int'>
<class 'float'>


In [28]:
arr = np.array([1, 2, 3.0])
# arr의 dtype은?
print(arr.dtype)



float64


# 3. 배열 변환

In [20]:
# 1차원 -> 2차원으로 변경
data = np.arange(0, 15)
print(data)
data2 = data.reshape(5, 3)
print(data2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
# 행열 전환 ( -> 행,  밑으로 열)
data3 = data2.transpose()
print(data2.shape)
print(data3)
print(data3.shape)

(5, 3)
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
(3, 5)


# 4. 연산

In [22]:
# 사칙연산 : 같은 위치에 있는 요소들끼리 계산됨
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = np.array([[10, 20, 30], [40, 50, 60]])

print(data1 + data2)
print(data1 - data2)
print(data1 * data2)
print(data1 / data2)

[[11 22 33]
 [44 55 66]]
[[ -9 -18 -27]
 [-36 -45 -54]]
[[ 10  40  90]
 [160 250 360]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


# 5. 통계

In [23]:
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = np.array([[10, 20, 30], [40, 50, 60]])

# sum, mean, var, std
print(data1.sum())
print(np.sum(data1))
print(np.sum(data1, axis=0))
print("="*50)
print(data1.mean())
print(np.mean(data1))
print(np.mean(data1, axis=0))
print("="*50)
print(data1.var())
print(np.var(data1))
print(np.var(data1, axis=0))
print("="*50)
print(data1.std())
print(np.std(data1))
print(np.std(data1, axis=0))

21
21
[5 7 9]
3.5
3.5
[2.5 3.5 4.5]
2.9166666666666665
2.9166666666666665
[2.25 2.25 2.25]
1.707825127659933
1.707825127659933
[1.5 1.5 1.5]


In [24]:
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ],
])

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=2))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[12 15 18]
 [39 42 45]]
[[ 6 15 24]
 [33 42 51]]


# 6. 실습

In [25]:
from PIL import Image 
from IPython.display import display 

image = Image.open("resources/dog.jpg")
display(image)

FileNotFoundError: [Errno 2] No such file or directory: 'resources/dog.jpg'

In [ ]:
import numpy as np 
image_arr = np.array(image)
print(image_arr.ndim)
print(image_arr.shape)
print(image_arr)

3
(439, 600, 3)
[[[106 119  39]
  [106 119  39]
  [107 120  40]
  ...
  [216 232 255]
  [218 234 255]
  [218 234 255]]

 [[105 118  38]
  [106 119  39]
  [107 120  40]
  ...
  [216 232 255]
  [217 233 255]
  [218 234 255]]

 [[105 118  39]
  [105 118  39]
  [106 119  40]
  ...
  [215 231 255]
  [216 232 255]
  [216 232 255]]

 ...

 [[104 134  74]
  [109 139  79]
  [112 140  81]
  ...
  [123 150  99]
  [107 130  84]
  [ 66  92  45]]

 [[ 81 111  51]
  [ 87 117  57]
  [ 91 119  60]
  ...
  [136 163 110]
  [104 130  82]
  [ 62  88  40]]

 [[ 74 103  45]
  [ 75 104  46]
  [ 79 107  48]
  ...
  [118 147  93]
  [ 90 118  67]
  [ 68  96  45]]]


In [ ]:
import numpy as np

def make_random_teams(student_list, team_size=3, seed=42):
    np.random.seed(seed)  # 항상 같은 결과를 위해 시드 고정
    shuffled = np.array(student_list)  # 원본 리스트를 복사하여 섞기
    np.random.shuffle(shuffled)

    num_teams = len(shuffled) // team_size
    teams = []
    for i in range(num_teams):
        team = shuffled[i * team_size : (i + 1) * team_size]
        teams.append(team)
    
    return teams

if __name__ == "__main__":
    students = [
        '강경란', '김서영', '김선재', '김유정', '박종욱', '백승주',
        '이성윤', '이연', '이재민', '이재진', '이진섭', '장찬영',
        '전민우', '전아연', '차요준', '최윤재', '황난혜', '황화인'
    ]

    teams = make_random_teams(students, seed=123)  # 원하는 seed 값 넣기

    for idx, team in enumerate(teams, 1):
        print(f"{idx}조: {team}")